### ISSUE TITLE
openCV是4.6还是4.7版本呢，我用4.7版本会报错。yolov8官方的example里面的cpp推理也会报错。不知道是不是安装错误了。

### ISSUE THREAD

**Issue by 7288Fzq** [hpc203/yolov8-face-landmarks-opencv-dnn#2]
控制台输出如下：

[ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_onetbb470_64d.dll => FAILED
[ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_onetbb470_64d.dll => FAILED
[ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_tbb470_64d.dll => FAILED
[ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_tbb470_64d.dll => FAILED
[ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_openmp470_64d.dll => FAILED
[ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_openmp470_64d.dll => FAILED

**Comment by 7288Fzq** [comment]
重装OpenCV好几次了没用

**Comment by hpc203** [comment]
> 控制台输出如下：
> 
> [ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_onetbb470_64d.dll => FAILED [ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_onetbb470_64d.dll => FAILED [ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_tbb470_64d.dll => FAILED [ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_tbb470_64d.dll => FAILED [ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_openmp470_64d.dll => FAILED [ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_openmp470_64d.dll => FAILED

C++版本的程序，用opencv4.7会报错的，使用opencv4.5的就可以

**Comment by 7288Fzq** [comment]
> > 控制台输出如下：
> > [ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_onetbb470_64d.dll => FAILED [ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_onetbb470_64d.dll => FAILED [ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_tbb470_64d.dll => FAILED [ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_tbb470_64d.dll => FAILED [ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_openmp470_64d.dll => FAILED [ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_openmp470_64d.dll => FAILED
> 
> C++版本的程序，用opencv4.7会报错的，使用opencv4.5的就可以

明白了。谢谢！！

**Comment by hpc203** [comment]
> 控制台输出如下：
> 
> [ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_onetbb470_64d.dll => FAILED [ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_onetbb470_64d.dll => FAILED [ INFO:0@0.228] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_tbb470_64d.dll => FAILED [ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_tbb470_64d.dll => FAILED [ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load C:\Windows\SYSTEM32\opencv_core_parallel_openmp470_64d.dll => FAILED [ INFO:0@0.229] global plugin_loader.impl.hpp:67 cv::plugin::impl::DynamicLib::libraryLoad load opencv_core_parallel_openmp470_64d.dll => FAILED

使用opencv4.7推理时，需要在net.forward之前加上net.enableWinograd(false);
