### ISSUE TITLE
.cpp程序报错

### ISSUE THREAD

**Issue by HouzhenyuEmile** [hpc203/yolov8-face-landmarks-opencv-dnn#6]
Ubuntu 20.04 系统，OpenCV尝试了4.5.5版本和4.7版本，验证了模型文件.onnx无错误，在使用onnxruntime和main.cpp两种部署方式时均返回下述报错

terminate called after throwing an instance of 'cv::Exception'
what():  OpenCV(4.5.5) /home/hou/opencv-4.5.5/modules/dnn/src/onnx/onnx_importer.cpp:709: error: (-215:Assertion failed) model_proto.has_graph() in function 'populateNet'

已放弃 (核心已转储)

大佬知道这是什么原因吗

**Comment by liuhuan1111** [comment]
我遇到过的时候是通过更改numpy库的版本解决的，你可以参考一下
